#!/usr/bin/env node
const { summarizeScheduleState, writeRuntimeStatusDocs, updateProjectStatusFromSchedule } = require("./agent-scheduling-lib.js");

const summary = writeRuntimeStatusDocs();
updateProjectStatusFromSchedule(summary);
console.log(JSON.stringify(summary, null, 2));
