import { readFile } from "node:fs/promises";
import path from "node:path";
import { AdminShell } from "@/components/admin/AdminShell";

interface BugReport {
  id: string;
  title: string;
  severity: string;
  category: string;
  status: string;
  module: string;
  summary?: string;
  assignedAgents?: string[];
  createdAt?: string;
  routePath?: string;
  pageContext?: {
    pageLabel?: string;
  };
  triageNotes?: string[];
}

async function readBugReports(): Promise<BugReport[]> {
  const filePath = path.join(process.cwd(), "data", "runtime", "bug-reports.json");
  try {
    const raw = await readFile(filePath, "utf8");
    const parsed = JSON.parse(raw) as { reports?: BugReport[] };
    return parsed.reports || [];
  } catch {
    return [];
  }
}

export default async function BugReportsPage() {
  const reports = await readBugReports();

  return (
    <AdminShell>
      <div className="space-y-6 p-5 lg:p-8">
        <div>
          <p className="text-sm font-semibold uppercase text-slate-500">RouteTrust bug runtime</p>
          <h1 className="mt-2 text-3xl font-bold text-slate-950">Bug Reports</h1>
          <p className="mt-2 text-sm text-slate-600">Local triage queue generated by the supervised runtime.</p>
        </div>

        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {reports.length === 0 ? (
            <div className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm">
              <p className="text-sm text-slate-500">No bug reports stored yet.</p>
            </div>
          ) : (
            reports.map((report) => (
              <div key={report.id} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex items-center justify-between gap-3">
                  <p className="text-sm font-semibold text-slate-950">{report.title}</p>
                  <span className="rounded-full border border-slate-200 px-3 py-1 text-xs font-bold uppercase text-slate-700">
                    {report.severity}
                  </span>
                </div>
                <p className="mt-2 text-sm text-slate-600">
                  {report.pageContext?.pageLabel || report.routePath || "Unknown page"} · {report.module}
                </p>
                <p className="mt-1 text-xs uppercase text-slate-500">
                  {report.category} · {report.status}
                </p>
                <p className="mt-3 text-xs text-slate-500">{report.assignedAgents?.join(", ") || "No agents assigned yet."}</p>
                {report.triageNotes?.length ? (
                  <div className="mt-3 rounded-md bg-slate-50 p-3">
                    <p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">Triage notes</p>
                    <p className="mt-1 text-xs text-slate-600">{report.triageNotes[0]}</p>
                  </div>
                ) : null}
              </div>
            ))
          )}
        </div>
      </div>
    </AdminShell>
  );
}
